//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfig) DeepCopyInto(out *AWSConfig) {
	*out = *in
	if in.AWSAccessKeySecret != nil {
		in, out := &in.AWSAccessKeySecret, &out.AWSAccessKeySecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfig.
func (in *AWSConfig) DeepCopy() *AWSConfig {
	if in == nil {
		return nil
	}
	out := new(AWSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogstreamConfig) DeepCopyInto(out *AuditLogstreamConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogstreamConfig.
func (in *AuditLogstreamConfig) DeepCopy() *AuditLogstreamConfig {
	if in == nil {
		return nil
	}
	out := new(AuditLogstreamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Automation) DeepCopyInto(out *Automation) {
	*out = *in
	if in.Workflow != nil {
		in, out := &in.Workflow, &out.Workflow
		*out = make([]AutomationStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Automation.
func (in *Automation) DeepCopy() *Automation {
	if in == nil {
		return nil
	}
	out := new(Automation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomationStep) DeepCopyInto(out *AutomationStep) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomationStep.
func (in *AutomationStep) DeepCopy() *AutomationStep {
	if in == nil {
		return nil
	}
	out := new(AutomationStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	if in.EvaluationInterval != nil {
		in, out := &in.EvaluationInterval, &out.EvaluationInterval
		*out = new(monitoringv1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JoinTransformer) DeepCopyInto(out *JoinTransformer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JoinTransformer.
func (in *JoinTransformer) DeepCopy() *JoinTransformer {
	if in == nil {
		return nil
	}
	out := new(JoinTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsConfig) DeepCopyInto(out *LogsConfig) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3LogsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Otlp != nil {
		in, out := &in.Otlp, &out.Otlp
		*out = new(OtlpLogsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsConfig.
func (in *LogsConfig) DeepCopy() *LogsConfig {
	if in == nil {
		return nil
	}
	out := new(LogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogstreamConfig) DeepCopyInto(out *LogstreamConfig) {
	*out = *in
	if in.MinSeverity != nil {
		in, out := &in.MinSeverity, &out.MinSeverity
		*out = new(SeverityLevel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogstreamConfig.
func (in *LogstreamConfig) DeepCopy() *LogstreamConfig {
	if in == nil {
		return nil
	}
	out := new(LogstreamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiCollector) DeepCopyInto(out *MdaiCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiCollector.
func (in *MdaiCollector) DeepCopy() *MdaiCollector {
	if in == nil {
		return nil
	}
	out := new(MdaiCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiCollectorList) DeepCopyInto(out *MdaiCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MdaiCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiCollectorList.
func (in *MdaiCollectorList) DeepCopy() *MdaiCollectorList {
	if in == nil {
		return nil
	}
	out := new(MdaiCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiCollectorSpec) DeepCopyInto(out *MdaiCollectorSpec) {
	*out = *in
	if in.AWSConfig != nil {
		in, out := &in.AWSConfig, &out.AWSConfig
		*out = new(AWSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(LogsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiCollectorSpec.
func (in *MdaiCollectorSpec) DeepCopy() *MdaiCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(MdaiCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiCollectorStatus) DeepCopyInto(out *MdaiCollectorStatus) {
	*out = *in
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiCollectorStatus.
func (in *MdaiCollectorStatus) DeepCopy() *MdaiCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(MdaiCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHub) DeepCopyInto(out *MdaiHub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHub.
func (in *MdaiHub) DeepCopy() *MdaiHub {
	if in == nil {
		return nil
	}
	out := new(MdaiHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiHub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHubList) DeepCopyInto(out *MdaiHubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MdaiHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHubList.
func (in *MdaiHubList) DeepCopy() *MdaiHubList {
	if in == nil {
		return nil
	}
	out := new(MdaiHubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiHubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHubSpec) DeepCopyInto(out *MdaiHubSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(Config)
		(*in).DeepCopyInto(*out)
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]Variable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrometheusAlert != nil {
		in, out := &in.PrometheusAlert, &out.PrometheusAlert
		*out = make([]PrometheusAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Automations != nil {
		in, out := &in.Automations, &out.Automations
		*out = make([]Automation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHubSpec.
func (in *MdaiHubSpec) DeepCopy() *MdaiHubSpec {
	if in == nil {
		return nil
	}
	out := new(MdaiHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHubStatus) DeepCopyInto(out *MdaiHubStatus) {
	*out = *in
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHubStatus.
func (in *MdaiHubStatus) DeepCopy() *MdaiHubStatus {
	if in == nil {
		return nil
	}
	out := new(MdaiHubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiObserver) DeepCopyInto(out *MdaiObserver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiObserver.
func (in *MdaiObserver) DeepCopy() *MdaiObserver {
	if in == nil {
		return nil
	}
	out := new(MdaiObserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiObserver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiObserverList) DeepCopyInto(out *MdaiObserverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MdaiObserver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiObserverList.
func (in *MdaiObserverList) DeepCopy() *MdaiObserverList {
	if in == nil {
		return nil
	}
	out := new(MdaiObserverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiObserverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiObserverSpec) DeepCopyInto(out *MdaiObserverSpec) {
	*out = *in
	if in.Observers != nil {
		in, out := &in.Observers, &out.Observers
		*out = make([]Observer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ObserverResource.DeepCopyInto(&out.ObserverResource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiObserverSpec.
func (in *MdaiObserverSpec) DeepCopy() *MdaiObserverSpec {
	if in == nil {
		return nil
	}
	out := new(MdaiObserverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiObserverStatus) DeepCopyInto(out *MdaiObserverStatus) {
	*out = *in
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiObserverStatus.
func (in *MdaiObserverStatus) DeepCopy() *MdaiObserverStatus {
	if in == nil {
		return nil
	}
	out := new(MdaiObserverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Observer) DeepCopyInto(out *Observer) {
	*out = *in
	if in.LabelResourceAttributes != nil {
		in, out := &in.LabelResourceAttributes, &out.LabelResourceAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CountMetricName != nil {
		in, out := &in.CountMetricName, &out.CountMetricName
		*out = new(string)
		**out = **in
	}
	if in.BytesMetricName != nil {
		in, out := &in.BytesMetricName, &out.BytesMetricName
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(ObserverFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(ObserverLogsConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Observer.
func (in *Observer) DeepCopy() *Observer {
	if in == nil {
		return nil
	}
	out := new(Observer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserverFilter) DeepCopyInto(out *ObserverFilter) {
	*out = *in
	if in.ErrorMode != nil {
		in, out := &in.ErrorMode, &out.ErrorMode
		*out = new(string)
		**out = **in
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(ObserverLogsFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserverFilter.
func (in *ObserverFilter) DeepCopy() *ObserverFilter {
	if in == nil {
		return nil
	}
	out := new(ObserverFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserverLogsConfig) DeepCopyInto(out *ObserverLogsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserverLogsConfig.
func (in *ObserverLogsConfig) DeepCopy() *ObserverLogsConfig {
	if in == nil {
		return nil
	}
	out := new(ObserverLogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserverLogsFilter) DeepCopyInto(out *ObserverLogsFilter) {
	*out = *in
	if in.LogRecord != nil {
		in, out := &in.LogRecord, &out.LogRecord
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserverLogsFilter.
func (in *ObserverLogsFilter) DeepCopy() *ObserverLogsFilter {
	if in == nil {
		return nil
	}
	out := new(ObserverLogsFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserverResource) DeepCopyInto(out *ObserverResource) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.GrpcReceiverMaxMsgSize != nil {
		in, out := &in.GrpcReceiverMaxMsgSize, &out.GrpcReceiverMaxMsgSize
		*out = new(uint64)
		**out = **in
	}
	if in.OwnLogsOtlpEndpoint != nil {
		in, out := &in.OwnLogsOtlpEndpoint, &out.OwnLogsOtlpEndpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserverResource.
func (in *ObserverResource) DeepCopy() *ObserverResource {
	if in == nil {
		return nil
	}
	out := new(ObserverResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtlpLogsConfig) DeepCopyInto(out *OtlpLogsConfig) {
	*out = *in
	if in.AuditLogs != nil {
		in, out := &in.AuditLogs, &out.AuditLogs
		*out = new(AuditLogstreamConfig)
		**out = **in
	}
	if in.CollectorLogs != nil {
		in, out := &in.CollectorLogs, &out.CollectorLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HubLogs != nil {
		in, out := &in.HubLogs, &out.HubLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OtherLogs != nil {
		in, out := &in.OtherLogs, &out.OtherLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtlpLogsConfig.
func (in *OtlpLogsConfig) DeepCopy() *OtlpLogsConfig {
	if in == nil {
		return nil
	}
	out := new(OtlpLogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusAlert) DeepCopyInto(out *PrometheusAlert) {
	*out = *in
	out.Expr = in.Expr
	if in.For != nil {
		in, out := &in.For, &out.For
		*out = new(monitoringv1.Duration)
		**out = **in
	}
	if in.KeepFiringFor != nil {
		in, out := &in.KeepFiringFor, &out.KeepFiringFor
		*out = new(monitoringv1.NonEmptyDuration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusAlert.
func (in *PrometheusAlert) DeepCopy() *PrometheusAlert {
	if in == nil {
		return nil
	}
	out := new(PrometheusAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3LogsConfig) DeepCopyInto(out *S3LogsConfig) {
	*out = *in
	if in.AuditLogs != nil {
		in, out := &in.AuditLogs, &out.AuditLogs
		*out = new(AuditLogstreamConfig)
		**out = **in
	}
	if in.CollectorLogs != nil {
		in, out := &in.CollectorLogs, &out.CollectorLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HubLogs != nil {
		in, out := &in.HubLogs, &out.HubLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OtherLogs != nil {
		in, out := &in.OtherLogs, &out.OtherLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3LogsConfig.
func (in *S3LogsConfig) DeepCopy() *S3LogsConfig {
	if in == nil {
		return nil
	}
	out := new(S3LogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Serializer) DeepCopyInto(out *Serializer) {
	*out = *in
	if in.Transformers != nil {
		in, out := &in.Transformers, &out.Transformers
		*out = make([]VariableTransformer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Serializer.
func (in *Serializer) DeepCopy() *Serializer {
	if in == nil {
		return nil
	}
	out := new(Serializer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Variable) DeepCopyInto(out *Variable) {
	*out = *in
	if in.VariableRefs != nil {
		in, out := &in.VariableRefs, &out.VariableRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SerializeAs != nil {
		in, out := &in.SerializeAs, &out.SerializeAs
		*out = make([]Serializer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Variable.
func (in *Variable) DeepCopy() *Variable {
	if in == nil {
		return nil
	}
	out := new(Variable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableTransformer) DeepCopyInto(out *VariableTransformer) {
	*out = *in
	if in.Join != nil {
		in, out := &in.Join, &out.Join
		*out = new(JoinTransformer)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableTransformer.
func (in *VariableTransformer) DeepCopy() *VariableTransformer {
	if in == nil {
		return nil
	}
	out := new(VariableTransformer)
	in.DeepCopyInto(out)
	return out
}
