//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.VariableUpdate != nil {
		in, out := &in.VariableUpdate, &out.VariableUpdate
		*out = new(VariableUpdate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	if in.EvaluationInterval != nil {
		in, out := &in.EvaluationInterval, &out.EvaluationInterval
		*out = new(monitoringv1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Evaluation) DeepCopyInto(out *Evaluation) {
	*out = *in
	out.Expr = in.Expr
	if in.For != nil {
		in, out := &in.For, &out.For
		*out = new(monitoringv1.Duration)
		**out = **in
	}
	if in.KeepFiringFor != nil {
		in, out := &in.KeepFiringFor, &out.KeepFiringFor
		*out = new(monitoringv1.NonEmptyDuration)
		**out = **in
	}
	if in.RelevantLabels != nil {
		in, out := &in.RelevantLabels, &out.RelevantLabels
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.OnStatus != nil {
		in, out := &in.OnStatus, &out.OnStatus
		*out = new(PrometheusAlertEvaluationStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Evaluation.
func (in *Evaluation) DeepCopy() *Evaluation {
	if in == nil {
		return nil
	}
	out := new(Evaluation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JoinTransformer) DeepCopyInto(out *JoinTransformer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JoinTransformer.
func (in *JoinTransformer) DeepCopy() *JoinTransformer {
	if in == nil {
		return nil
	}
	out := new(JoinTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHub) DeepCopyInto(out *MdaiHub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHub.
func (in *MdaiHub) DeepCopy() *MdaiHub {
	if in == nil {
		return nil
	}
	out := new(MdaiHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiHub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHubList) DeepCopyInto(out *MdaiHubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MdaiHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHubList.
func (in *MdaiHubList) DeepCopy() *MdaiHubList {
	if in == nil {
		return nil
	}
	out := new(MdaiHubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiHubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHubSpec) DeepCopyInto(out *MdaiHubSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(Config)
		(*in).DeepCopyInto(*out)
	}
	if in.Observers != nil {
		in, out := &in.Observers, &out.Observers
		*out = new([]Observer)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Observer, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.ObserverResources != nil {
		in, out := &in.ObserverResources, &out.ObserverResources
		*out = new([]ObserverResource)
		if **in != nil {
			in, out := *in, *out
			*out = make([]ObserverResource, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = new([]Variable)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Variable, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Evaluations != nil {
		in, out := &in.Evaluations, &out.Evaluations
		*out = new([]Evaluation)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Evaluation, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHubSpec.
func (in *MdaiHubSpec) DeepCopy() *MdaiHubSpec {
	if in == nil {
		return nil
	}
	out := new(MdaiHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHubStatus) DeepCopyInto(out *MdaiHubStatus) {
	*out = *in
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHubStatus.
func (in *MdaiHubStatus) DeepCopy() *MdaiHubStatus {
	if in == nil {
		return nil
	}
	out := new(MdaiHubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Observer) DeepCopyInto(out *Observer) {
	*out = *in
	if in.LabelResourceAttributes != nil {
		in, out := &in.LabelResourceAttributes, &out.LabelResourceAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CountMetricName != nil {
		in, out := &in.CountMetricName, &out.CountMetricName
		*out = new(string)
		**out = **in
	}
	if in.BytesMetricName != nil {
		in, out := &in.BytesMetricName, &out.BytesMetricName
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(ObserverFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Observer.
func (in *Observer) DeepCopy() *Observer {
	if in == nil {
		return nil
	}
	out := new(Observer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserverFilter) DeepCopyInto(out *ObserverFilter) {
	*out = *in
	if in.ErrorMode != nil {
		in, out := &in.ErrorMode, &out.ErrorMode
		*out = new(string)
		**out = **in
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(ObserverLogsFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserverFilter.
func (in *ObserverFilter) DeepCopy() *ObserverFilter {
	if in == nil {
		return nil
	}
	out := new(ObserverFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserverLogsFilter) DeepCopyInto(out *ObserverLogsFilter) {
	*out = *in
	if in.LogRecord != nil {
		in, out := &in.LogRecord, &out.LogRecord
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserverLogsFilter.
func (in *ObserverLogsFilter) DeepCopy() *ObserverLogsFilter {
	if in == nil {
		return nil
	}
	out := new(ObserverLogsFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserverResource) DeepCopyInto(out *ObserverResource) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.GrpcReceiverMaxMsgSize != nil {
		in, out := &in.GrpcReceiverMaxMsgSize, &out.GrpcReceiverMaxMsgSize
		*out = new(uint64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserverResource.
func (in *ObserverResource) DeepCopy() *ObserverResource {
	if in == nil {
		return nil
	}
	out := new(ObserverResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusAlertEvaluationStatus) DeepCopyInto(out *PrometheusAlertEvaluationStatus) {
	*out = *in
	if in.Firing != nil {
		in, out := &in.Firing, &out.Firing
		*out = new(Action)
		(*in).DeepCopyInto(*out)
	}
	if in.Resolved != nil {
		in, out := &in.Resolved, &out.Resolved
		*out = new(Action)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusAlertEvaluationStatus.
func (in *PrometheusAlertEvaluationStatus) DeepCopy() *PrometheusAlertEvaluationStatus {
	if in == nil {
		return nil
	}
	out := new(PrometheusAlertEvaluationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Serializer) DeepCopyInto(out *Serializer) {
	*out = *in
	if in.Transformers != nil {
		in, out := &in.Transformers, &out.Transformers
		*out = make([]VariableTransformer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Serializer.
func (in *Serializer) DeepCopy() *Serializer {
	if in == nil {
		return nil
	}
	out := new(Serializer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Variable) DeepCopyInto(out *Variable) {
	*out = *in
	if in.SerializeAs != nil {
		in, out := &in.SerializeAs, &out.SerializeAs
		*out = make([]Serializer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Variable.
func (in *Variable) DeepCopy() *Variable {
	if in == nil {
		return nil
	}
	out := new(Variable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableTransformer) DeepCopyInto(out *VariableTransformer) {
	*out = *in
	if in.Join != nil {
		in, out := &in.Join, &out.Join
		*out = new(JoinTransformer)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableTransformer.
func (in *VariableTransformer) DeepCopy() *VariableTransformer {
	if in == nil {
		return nil
	}
	out := new(VariableTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableUpdate) DeepCopyInto(out *VariableUpdate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableUpdate.
func (in *VariableUpdate) DeepCopy() *VariableUpdate {
	if in == nil {
		return nil
	}
	out := new(VariableUpdate)
	in.DeepCopyInto(out)
	return out
}
