{{- if (not .Values.webhooks.certManager.enabled) }}
{{- $cert := fromYaml (include "deployment.webhookCert" .) }}
{{- $caCertEnc := $cert.ca }}
{{- $certCrtEnc := $cert.crt }}
{{- $certKeyEnc := $cert.key }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  name: webhook-server-cert
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ $certCrtEnc }}
  tls.key: {{ $certKeyEnc }}
  ca.crt: {{ $caCertEnc }}
  {{- end }}