apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "deployment.fullname" . }}-manager-role
  labels:
  {{- include "deployment.labels" . | nindent 4 }}
rules:
- apiGroups:
  - mdai.mdai.ai
  resources:
  - mdaihubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mdai.mdai.ai
  resources:
  - mdaihubs/finalizers
  verbs:
  - update
- apiGroups:
  - mdai.mdai.ai
  resources:
  - mdaihubs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "deployment.fullname" . }}-manager-rolebinding
  labels:
  {{- include "deployment.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "deployment.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "deployment.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'