apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "deployment.fullname" . }}-mdaiobserver-admin-role
  labels:
  {{- include "deployment.labels" . | nindent 4 }}
rules:
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaiobservers
  verbs:
  - '*'
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaiobservers/status
  verbs:
  - get
