apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "deployment.fullname" . }}-mdaireplay-editor-role
  labels:
  {{- include "deployment.labels" . | nindent 4 }}
rules:
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaireplays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaireplays/status
  verbs:
  - get
