apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "deployment.fullname" . }}-mdaicollector-viewer-role
  labels:
  {{- include "deployment.labels" . | nindent 4 }}
rules:
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaicollectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaicollectors/status
  verbs:
  - get