{{- if and (.Values.admissionWebhooks.create) (.Values.admissionWebhooks.certManager.enabled) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "deployment.fullname" . }}-metrics-certs
  labels:
  {{- include "deployment.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "deployment.fullname" . }}-controller-manager-metrics-service.{{ .Release.Namespace
    }}.svc'
  - '{{ include "deployment.fullname" . }}-controller-manager-metrics-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "deployment.fullname" . }}-selfsigned-issuer'
  secretName: metrics-server-cert
{{- end }}