{{- if and (.Values.admissionWebhooks.create) (not .Values.admissionWebhooks.certManager.enabled) }}
{{- $cert := fromYaml (include "mdai-operator.WebhookCert" .) }}
{{- $caCertEnc := $cert.ca }}
{{- $certCrtEnc := $cert.crt }}
{{- $certKeyEnc := $cert.key }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "deployment.fullname" . }}-mutating-webhook-configuration
  annotations:
  labels:
  {{- include "deployment.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $caCertEnc }}
    service:
      name: '{{ include "deployment.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-hub-mydecisive-ai-v1-mdaihub
  failurePolicy: Fail
  name: mmdaihub-v1.kb.io
  rules:
  - apiGroups:
    - hub.mydecisive.ai
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mdaihubs
  sideEffects: None
{{- and }}
