{{- if and (.Values.admissionWebhooks.create) (not .Values.admissionWebhooks.certManager.enabled) }}
{{- $cert := fromYaml (include "mdai-operator.WebhookCert" .) }}
{{- $caCertEnc := $cert.ca }}
{{- $certCrtEnc := $cert.crt }}
{{- $certKeyEnc := $cert.key }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  labels:
    app.kubernetes.io/component: webhook
  name:  webhook-server-cert
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: "{{ $certCrtEnc }}"
  tls.key: "{{ $certKeyEnc }}"
  ca.crt: "{{ $caCertEnc }}"
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  labels:
    app.kubernetes.io/component: webhook
  name:  metrics-server-cert
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: "{{ $certCrtEnc }}"
  tls.key: "{{ $certKeyEnc }}"
  ca.crt: "{{ $caCertEnc }}"
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "deployment.fullname" . }}-mutating-webhook-configuration
  annotations:
  labels:
  {{- include "deployment.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $caCertEnc }}
    service:
      name: '{{ include "deployment.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-hub-mydecisive-ai-v1-mdaihub
  failurePolicy: Fail
  name: mmdaihub-v1.kb.io
  rules:
  - apiGroups:
    - hub.mydecisive.ai
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mdaihubs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $caCertEnc }}
    service:
      name: '{{ include "deployment.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-hub-mydecisive-ai-v1-mdaiingress
  failurePolicy: Fail
  name: mmdaiingress-v1.kb.io
  rules:
  - apiGroups:
    - hub.mydecisive.ai
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mdaiingresses
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "deployment.fullname" . }}-validating-webhook-configuration
  annotations:
  labels:
  {{- include "deployment.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $caCertEnc }}
    service:
      name: '{{ include "deployment.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-hub-mydecisive-ai-v1-mdaicollector
  failurePolicy: Fail
  name: vmdaicollector-v1.kb.io
  rules:
  - apiGroups:
    - hub.mydecisive.ai
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mdaicollectors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $caCertEnc }}
    service:
      name: '{{ include "deployment.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-hub-mydecisive-ai-v1-mdaihub
  failurePolicy: Fail
  name: vmdaihub-v1.kb.io
  rules:
  - apiGroups:
    - hub.mydecisive.ai
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mdaihubs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $caCertEnc }}
    service:
      name: '{{ include "deployment.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-hub-mydecisive-ai-v1-mdaiingress
  failurePolicy: Fail
  name: vmdaiingress-v1.kb.io
  rules:
  - apiGroups:
    - hub.mydecisive.ai
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mdaingresses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $caCertEnc }}
    service:
      name: '{{ include "deployment.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-hub-mydecisive-ai-v1-mdaiobserver
  failurePolicy: Fail
  name: vmdaiobserver-v1.kb.io
  rules:
  - apiGroups:
    - hub.mydecisive.ai
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mdaiobservers
  sideEffects: None
{{- end }}