apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}-webhook-service
  labels:
  {{- include "deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    app.kubernetes.io/name: mdai-operator
    control-plane: controller-manager
    {{- include "deployment.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}
