apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-templates
  namespace: mdai
data:
  pagerduty.json: |
    {
      "routing_key": "${template:routing_key}",
      "event_action": "trigger",
      "payload": {
        "summary": "${trigger:payload.labels.alertname} on ${trigger:payload.labels.mdai_service}",
        "source":  "${trigger:payload.labels.instance}",
        "severity":"${template:severity:-error}",
        "custom_details": {
          "hub":  "${trigger:hub_name}",
          "corr": "${trigger:correlation_id}"
        }
      }
    }

  # GitHub Actions workflow_dispatch
  github-workflow.json: |
    {
      "ref":   "${template:ref:-main}",
      "inputs": {
        "env":      "${template:env:-prod}",
        "build_id": "${trigger:id}"
      }
    }

  # ServiceNow incident
  servicenow-incident.json: |
    {
      "short_description": "Auto incident: ${trigger:payload.labels.alertname}",
      "description": "Service: ${trigger:payload.labels.mdai_service}\nCorr: ${trigger:correlation_id}",
      "urgency": "${template:urgency:-2}",
      "impact":  "${template:impact:-2}"
    }

  # Generic JSON envelope
  generic.json: |
    {
      "message": "${template:message:-MDAI event}",
      "hub":     "${trigger:hub_name}",
      "corr":    "${trigger:correlation_id}",
      "raw":     "${trigger:payload}"
    }