# permissions for end users to edit mdaihubs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-editor-role
rules:
- apiGroups:
  - mdai.mdai.ai
  resources:
  - mdaihubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mdai.mdai.ai
  resources:
  - mdaihubs/status
  verbs:
  - get
