# This rule is not used by the project mdai-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the hub.mydecisive.ai.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaiobserver-editor-role
rules:
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaiobservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaiobservers/status
  verbs:
  - get
