# permissions for end users to view mdaihubs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-viewer-role
rules:
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaihubs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaihubs/status
  verbs:
  - get
