# This rule is not used by the project mdai-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over hub.mydecisive.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaicollector-admin-role
rules:
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaicollectors
  verbs:
  - '*'
- apiGroups:
  - hub.mydecisive.ai
  resources:
  - mdaicollectors/status
  verbs:
  - get
