controllerManager:
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect=false
    - --health-probe-bind-address=:8081
    - --metrics-cert-path=/tmp/k8s-metrics-server/metrics-certs
    - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    env:
      valkeyAuditStreamExpiryMs: "2592000000"
    image:
      repository: public.ecr.aws/p3k6k6h3/mdai-operator
      tag: 0.1.7
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
webhooks:
  certManager:
    enabled: true
  autoGenerateCert:
    enabled: false
    certValidDays: 3650
