apiVersion: hub.mydecisive.ai/v1
kind: MdaiReplay
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaireplay-sample
spec:
  # TODO(user): Add fields here
