apiVersion: hub.mydecisive.ai/v1
kind: MdaiCollector
metadata:
  namespace: mdai
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: hubcollector
spec:
  aws:
   awsAccessKeySecret: aws-credentials
  logs:
   s3:
     s3Region: "us-east-1"
     s3Bucket: "mdai-collector-logs"
