apiVersion: mdai.mdai.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-sample
spec:
  config:
    reconcileLoopInterval: 3m
  variables:
    - name: service_list
      storageType: "mdai-valkey"
      type: "array"
      delimiter: "|"
      defaultValue: "n/a"
    - name: service
      storageType: "mdai-valkey"
      type: "scalar"
  evaluations:
    - name: evaluation-1
      evaluationType: prometheus
      alertingRules:
        - name: daily
          alert_query: 'increase(mdai_log_bytes_sent_total{service_name="service1"}[24h]) > 2*1024*1024*1024'
          for: 10m
          severity: critical
          action: toggleFilter
        - name: hourly
          alert_query: 'increase(mdai_log_bytes_sent_total[1h]) > 100*1024*1024'
          for: 5m
          severity: warning
          action: manageFilter
  events:
    - name: event-1
  observers:
    - name: observer-1
