apiVersion: mdai.mdai.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-sample
spec:
  observers:
    - name: error_logs_by_node_observer
      metricName: error_logs_by_node
      evaluation: "log_level IN 'WARN'|'CRITICAL'"
      transformation: incrementBy('node_name')
  variables:
    - name: log_error_rate_window
      sourceType: "mdai-valkey"
      type: "scalar"
      defaultValue: "4m"
    - name: node_max_errors
      sourceType: "mdai-valkey"
      type: "scalar"
      defaultValue: 300
    - name: node_restart_max_count
      sourceType: "mdai-valkey"
      type: "scalar"
      defaultValue: 3
    - name: node_average_error_rate
      sourceType: "mdai-valkey"
      defaultValue: 999999999
  evaluations:
    - name: nodeAverageErrorRate
      expr: "average(increase(error_logs_by_node))"
      severity: warning
      interval: "1h"
    - name: nodeIsErrored
      expr: "(sum(increase(error_logs_by_node)) > {{mdai_variable.node_max_errors}} by node_name) OR (sum(increase(error_logs_by_node) > ({{mdai_variable.node_average_error_rate}} * 1.1) by node_name)"
      for: mdai_variable.log_error_rate_window
  triggers:
    - name: calculateAverageNodeErrorRate
      evaluationName: nodeAverageErrorRate
      evaluationType: prometheus
    - name: nodeIsInErroredState
      evaluationName: nodeIsErrored
      relevantLabels:
        - "node_name"
      evaluationType: prometheus
    - name: nodeHasNotRestarted
      evaluationType: expression
      evaluation: "restart_count_{{labels[0]}}" == nil || "restart_count_{{labels[0]}}" == 0
    - name: restartNodeAgain
      evaluationType: expression
      evaluation: "restart_count_{{labels[0]}}" != nil && "restart_count_{{labels[0]}}" < mdai_variable.node_restart_max_count
    - name: rollbackNode
      evaluationType: expression
      evaluation: "restart_count_{{labels[0]}}" == mdai_variable.node_restart_max_count
  actions:
    - name: replaceNodeErrorRate
      action_type: mdai/update_variable
      operation: replace
      variable_name: node_average_error_rate
    - name: erroredNodeRestart
      action_type: mdai/network_call
      url: https://your.cd.cd.pipeline/restart/node
      headers:
        some: "auth"
        stuff: "here"
    - name: erroredNodeRollback
      action_type: mdai/network_call
      url: https://your.cd.cd.pipeline/rollback/node
      headers:
        some: "auth"
        stuff: "here"
    - name: beginNodeRestartCount
      action_type: mdai/update_variable
      variable_name: "restart_count_{{labels[0]}}"
      operation: replace
      value: 1
    - name: incrementNodeRestartCount
      action_type: mdai/update_variable
      variable_name: "restart_count_{{labels[0]}}"
      operation: increment
    - name: resetNodeRestartCount
      action_type: mdai/update_variable
      variable_name: "restart_count{{labels[0]}}"
      operation: replace
      value: 0
  eventMap:
    calculateAverageNodeErrorRate:
      - replaceNodeErrorRate
    nodeIsInErroredState:
      nodeHasNotRestarted:
        - erroredNodeRestart
        - beginNodeRestartCount
      restartNodeAgain:
        - erroredNodeRestart
        - incrementNodeRestartCount
      rollbackNode:
        - erroredNodeRollback
        - resetNodeRestartCount
