apiVersion: mdai.mdai.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-sample
spec:
  observers:
    - name: observer-1
  variables:
    - name: service_list
      sourceType: "mdai-valkey"
      type: "array"
      delimiter: "|"
      defaultValue: "n/a"
  evaluations:
    - name: logBytesOutTooHighBySvc
      expr: '(increase(mdai_log_bytes_sent_total[1h]) > 100*1024*1024) by service_name, team'
      for: 5m
      severity: warning
  triggers:
    - name: serviceLogsExceedThreshold
      evaluationName: logBytesOutTooHighBySvc
      alertStatus: 'firing'
      relevantLabels:
        - 'service_name'
        - 'team'
      evaluationType: prometheus
    - name: serviceLogsBelowThreshold
      evaluationName: logBytesOutTooHighBySvc
      alertStatus: 'resolved'
      relevantLabels:
        - 'service_name'
      evaluationType: prometheus
  actions:
    - name: addService
      action_type: mdai/update_variable
      operation: add
      variable_name: service_list
    - name: removeService
      action_type: mdai/update_variable
      operation: remove
      variable_name: service_list
    - name: pageTeam
      action_type: mdai/network_call
      url: http://www.pagerduty.com:8080/trigger
  eventMap:
    serviceLogsExceedThreshold:
      - addService
      - pageTeam
    serviceLogsBelowThreshold:
      - removeService
