apiVersion: hub.mydecisive.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-second
  namespace: mdai
spec:
  variables:
    - storageKey: service_list
      defaultValue: "n/a"
      type: set
      serializeAs:
        - name: "SERVICE_LIST_REGEX"
          transformer:
            join:
              delimiter: "|"

  observers:
    - name: service-bytes-watcher1
      resource: watcher-collector
      labelResourceAttributes:
      - service.name
      - team
      - region
      countMetricName: mdai_watcher_four_count_total
      bytesMetricName: mdai_watcher_four_bytes_total
      filter:
        error_mode: ignore
        logs:
          log_record:
            - 'attributes["log_level"] == "INFO"'

  observerResources:
    - name: watcher-collector
      image: public.ecr.aws/decisiveai/watcher-collector:0.1

  evaluations:
    - name: logBytesOutTooHighBySvc
      type: mdai/prometheus_alert
      expr: 'increase(mdai_log_bytes_sent_total[1h]) > 100*1024*1024'
      severity: warning
      onStatus:
        firing:
          variableUpdate:
            variableRef: service_list
            operation: mdai/add_element
        resolved:
          variableUpdate:
            variableRef: service_list
            operation: mdai/remove_element
      for: 5m
      keep_firing_for: 10m
      relevantLabels:
        - "service_name"
