apiVersion: mdai.mdai.ai/v1
# Put a brief introduction
kind: MdaiHub
# Metadata section for the resource
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-dynamic-data-filtering-sample
# Specification section for the MdaiHub resource
spec:
  config:
    reconcileLoopInterval: 3m
  # Variables whose values are managed by MDAI. Typical use is update by Action and converted to environment variables by the MDAI Operator.
  variables:
    - storageKey: service_list
      defaultValue: "n/a"
      with:
        - exportedVariableName: "SERVICE_LIST_REGEX"
          serialize: join("|")
        - exportedVariableName: "SERVICE_LIST_CSV"
          serialize: join(",")
      # below properties are optional
      type: set
      storageType: "mdai-valkey"

  # Observers that watch telemetry and contribute metrics to Prometheus. Typical use is to query these metrics in Evaluations.
  observers:
    - name: service-bytes
      image: public.ecr.aws/p3k6k6h3/watcher-observer
      config:
        attributes: "service.name"
  # Evaluations define the conditions to check. Currently, supported Evaluations are only Prometheus Alerts.
  evaluations:
    - name: logBytesOutTooHighBySvc
      type: mdai/prometheus_alert
      expr: '(increase(mdai_log_bytes_sent_total[1h]) > 100*1024*1024) by service_name'
      severity: warning
      resolvedStatus:
        firing:
          type: mdai/variable_update
          operation: mdai/add
        resolved:
          type: mdai/variable_update
          operation: mdai/remove
      # Optional below here
      for: 5m
      keep_firing_for: 10m
      relevantLabels:
        - "service_name"

