apiVersion: hub.mydecisive.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-sample
  namespace: mdai
spec:
  variables:
    - key: service_list_1
      dataType: set
      storageType: "mdai-valkey"
      serializeAs:
        - name: "SERVICE_LIST_REGEX"
          transformers:
            - type: join
              join:
                delimiter: "|"
        - name: "SERVICE_LIST_CSV"
          transformers:
            - type: join
              join:
                delimiter: ","
    - key: service_list_2
      dataType: set
      storageType: "mdai-valkey"
      serializeAs:
        - name: "SERVICE_LIST_2_REGEX"
          transformers:
            - type: join
              join:
                delimiter: "|"
        - name: "SERVICE_LIST_2_CSV"
          transformers:
            - type: join
              join:
                delimiter: ","

  observers:
    - name: watcher1
      resourceRef: watcher-collector
      labelResourceAttributes:
        - service.name
      countMetricName: mdai_watcher_one_count_total
      bytesMetricName: mdai_watcher_one_bytes_total
    - name: watcher2
      resourceRef: watcher-collector
      labelResourceAttributes:
      - team
      - log_level
      countMetricName: mdai_watcher_two_count_total
    - name: watcher3
      resourceRef: watcher-collector
      labelResourceAttributes:
      - region
      - log_level
      bytesMetricName: mdai_watcher_three_count_total
    - name: watcher4
      resourceRef: watcher-collector
      labelResourceAttributes:
      - service.name
      - team
      - region
      countMetricName: mdai_watcher_four_count_total
      bytesMetricName: mdai_watcher_four_bytes_total
      filter:
        error_mode: ignore
        logs:
          log_record:
            - 'attributes["log_level"] == "INFO"'

  observerResources:
    - name: watcher-collector
      grpcReceiverMaxMsgSize: 10
      image: public.ecr.aws/decisiveai/observer-collector:0.1

  prometheusAlert:
    - name: logBytesOutTooHighBySvc
      expr: 'increase(mdai_log_bytes_sent_total[1h]) > 100*1024*1024'
      severity: warning
      for: 5m
      keep_firing_for: 10m

