apiVersion: mdai.mdai.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-sample
spec:
  variables:
    - name: service-list
      source:
        type: "valkey"
      type: "scalar"
      delimiter: "|"
  actions:
    - name: addService
      action_type: update_variable
      operation: add
      variable_name: service-list
    - name: removeService
      action_type: update_variable
      operation: remove
      variable_name: service-list
  alerts:
    - name: hourly
      expr: '(increase(mdai_log_bytes_sent_total[1h]) > 100*1024*1024) by service_name'
      for: 5m
      severity: warning
  triggers:
    - name: serviceTooNoisyHourly
      evaluationType: prometheus
      alertingRuleName: hourly
      alertStatus: 'firing'
      relevantLabel: 'service_name'
    - name: serviceWentQuietHourly
      evaluationType: prometheus
      alertingRuleName: hourly
      alertStatus: 'resolved'
      relevantLabel: 'service_name'
  eventMap:
    serviceTooNoisyHourly:
      - addService
    serviceWentQuietHourly:
      - removeService
  observers:
    - name: observer-1
