apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        mdai_component_type: mdai-watcher
        prometheus.io/path: /metrics
        prometheus.io/port: "8899"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - command:
            - /mdai-watcher-collector
            - --config=/conf/collector.yaml
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              name: otelcol-metrics
              protocol: TCP
            - containerPort: 8899
              name: watcher-metrics
              protocol: TCP
            - containerPort: 4317
              name: otlp-grpc
              protocol: TCP
            - containerPort: 4318
              name: otlp-http
              protocol: TCP
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /conf/collector.yaml
              name: config-volume
              subPath: collector.yaml
