receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  k8s_events:
    namespaces:
      - '${env:K8S_NAMESPACE}'

processors:
  batch:
    send_batch_size: 1000
    send_batch_max_size: 10000
    timeout: 13s
  filter/severity:
    error_mode: ignore
    logs:
      log_record:
        - severity_number < ${env:LOG_SEVERITY} and attributes["mdaiHubEvent"] == nil
  resource/k8slogstream:
    attributes:
      - key: mdai-logstream
        value: "hub"
        action: upsert
  resource/hub-to-audit:
    attributes:
      - key: mdai-logstream
        value: "audit"
        action: upsert

exporters:
  debug: {}
  debug/verbose:
    verbosity: detailed

connectors:
  routing/logstream:
    default_pipelines: [logs/other]
    table:
      - context: log
        condition: attributes["mdaiHubEvent"] != nil
        pipelines: [logs/audit]
      - context: resource
        condition: attributes["mdai-logstream"] == "collector"
        pipelines: [logs/collector]
      - context: resource
        condition: attributes["mdai-logstream"] == "hub"
        pipelines: [logs/hub]

extensions:
  cgroupruntime:
    gomaxprocs:
      enabled: true
    gomemlimit:
      enabled: true

service:
  pipelines:
    logs/k8s_events:
      receivers: [k8s_events]
      processors: [resource/k8slogstream]
      exporters: [routing/logstream]
    logs/input:
      receivers: [otlp]
      processors: [filter/severity, batch]
      exporters: [routing/logstream]

    logs/audit:
      receivers: [routing/logstream]
      processors: [resource/hub-to-audit, batch]
      exporters: [debug]
    logs/hub:
      receivers: [routing/logstream]
      processors: [batch]
      exporters: [debug]
    logs/collector:
      receivers: [routing/logstream]
      processors: [batch]
      exporters: [debug]
    logs/other:
      receivers: [routing/logstream]
      processors: [filter/severity, batch]
      exporters: [debug]