name: Publish Helm Chart to GHCR

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  helm-publish:
    uses: DecisiveAI/ci/.github/workflows/helm-publish.yml@main
    secrets:
      SLACK_NOTIFY_URL: ${{ secrets.SLACK_NOTIFY_URL }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}