name: Docker push for main branch

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  helm-publish:
    uses: DecisiveAI/ci/.github/workflows/docker-push-to-ecr.yml@main
    secrets:
      SLACK_NOTIFY_URL: ${{ secrets.SLACK_NOTIFY_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}