name: E2E Tests

on:
  workflow_run:
    workflows: [ "Lint" ]
    types:
      - completed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GOPRIVATE: github.com/decisiveai/opentelemetry-operator
  TOKEN: ${{ secrets.TOKEN_OPERATOR }}

jobs:
  wait-for-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check if "Tests" ran
        id: check-tests
        run: |
          TESTS_RUN=$(gh run list --workflow "Tests" --branch "${{ github.event.workflow_run.head_branch }}" --repo "${{ github.repository }}" --json status --jq 'length > 0')
          echo "tests_ran=$TESTS_RUN" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Wait for "Tests" to complete (if it ran)
        if: env.tests_ran == 'true'
        run: |
          while gh run list --workflow "Tests" --branch "${{ github.event.workflow_run.head_branch }}" --json status --jq '.[] | select(.status != "completed")'; do
            echo "Waiting for 'Tests' to complete..."
            sleep 10
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-e2e:
    name: E2E tests on Ubuntu
    needs: wait-for-tests
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for private modules
        run: git config --global url."https://user:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster

      - name: Running Test e2e
        run: |
          go mod vendor
          go mod tidy
          make test-e2e
